/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.add-button[_ngcontent-%COMP%]{\n    margin: 12px;\n}\n\n.inline-fab[_ngcontent-%COMP%]{\n    margin-left: 12px;\n}\n\n.gig-list[_ngcontent-%COMP%]{\n    max-height: 70vh;\n    overflow-y: scroll;\n}\n\n.checkbox[_ngcontent-%COMP%]{\n    margin: 12px;\n}\n\na[_ngcontent-%COMP%] {\n    cursor: pointer;\n}\n\n.website-link[_ngcontent-%COMP%]{\n    vertical-align: middle;\n    cursor: pointer;\n    color: red;\n    font-size: 18px;\n}\n\n@media screen and (max-width: 959px){\n    .buy-tickets-large[_ngcontent-%COMP%]{\n        display: none;\n    }\n}\n\n@media screen and (min-width: 960px){\n    .buy-tickets-small[_ngcontent-%COMP%]{\n        display: none;\n    }\n}\nbutton[_ngcontent-%COMP%]{\n    margin-left: 50px;\n}\n\nmd-slide-toggle[_ngcontent-%COMP%]{\n    margin-left: 12px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvQ01TL2dpZ3MvZ2lncy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvQ01TL2dpZ3MvZ2lncy5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
