/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './bio.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../assets/app/CMS/bio/bio.component';
const styles_CmsBioComponent:any[] = [import0.styles];
export const RenderType_CmsBioComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_CmsBioComponent,
  data: {}
}
);
export function View_CmsBioComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    BIO\n']))
  ]
  ,(null as any),(null as any));
}
function View_CmsBioComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'cms-bio',([] as any[]),(null as any),(null as any),(null as any),View_CmsBioComponent_0,RenderType_CmsBioComponent)),
    import1.ɵdid(49152,(null as any),0,import2.CmsBioComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const CmsBioComponentNgFactory:import1.ComponentFactory<import2.CmsBioComponent> = import1.ɵccf('cms-bio',import2.CmsBioComponent,View_CmsBioComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvQ01TL2Jpby9iaW8uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvQ01TL2Jpby9iaW8uY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvam9ucm93ZS9Eb2N1bWVudHMvYW5ndWxhcjQvdmltYWxhdHYvYXNzZXRzL2FwcC9DTVMvYmlvL2Jpby5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvQ01TL2Jpby9iaW8uY29tcG9uZW50LnRzLkNtc0Jpb0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXY+XG4gICAgQklPXG48L2Rpdj4iLCI8Y21zLWJpbz48L2Ntcy1iaW8+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFLOzs7Ozs7SUNBTDtnQkFBQTs7OzsifQ==
