/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/flex-layout/flexbox/api/flex';
import * as import2 from '@angular/flex-layout/media-query/media-monitor';
import * as import3 from '@angular/flex-layout/flexbox/api/layout';
import * as import4 from '@angular/flex-layout/flexbox/api/layout-wrap';
import * as import5 from '@angular/flex-layout/flexbox/api/class';
import * as import6 from '../../../../../assets/app/Site/Collab/audio.component';
import * as import7 from '@angular/platform-browser';
const styles_AudioComponent:any[] = ['.audio-component[_ngcontent-%COMP%]{\n            margin: 10px;\n            padding: 10px;\n            max-width: 640px;\n            max-height: 480px;\n            width: auto;\n            height: auto;\n            color: white;\n        }'];
export const RenderType_AudioComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_AudioComponent,
  data: {}
}
);
export function View_AudioComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),5,'div',[
      [
        'class',
        'audio-component'
      ]
      ,
      [
        'fxFlex',
        ''
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    import0.ɵdid(737280,(null as any),0,import1.FlexDirective,[
      import2.MediaMonitor,
      import0.ElementRef,
      import0.Renderer2,
      [
        3,
        import3.LayoutDirective
      ]
      ,
      [
        3,
        import4.LayoutWrapDirective
      ]

    ]
      ,{flex: [
        0,
        'flex'
      ]
    },(null as any)),
    import0.ɵdid(933888,(null as any),0,import5.ClassDirective,[
      import2.MediaMonitor,
      import0.IterableDiffers,
      import0.KeyValueDiffers,
      import0.ElementRef,
      import0.Renderer,
      import0.Renderer2
    ]
      ,{classBase: [
        0,
        'classBase'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n            '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),0,'iframe',[
      [
        'frameborder',
        'no'
      ]
      ,
      [
        'height',
        '166'
      ]
      ,
      [
        'scrolling',
        'no'
      ]
      ,
      [
        'width',
        '100%'
      ]

    ]
      ,[[
        8,
        'src',
        5
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵted((null as any),['\n    ']))
  ]
  ,(ck,v) => {
    const currVal_0:any = '';
    ck(v,2,0,currVal_0);
    const currVal_1:any = 'audio-component';
    ck(v,3,0,currVal_1);
  },(ck,v) => {
    var co:import6.AudioComponent = v.component;
    const currVal_2:any = co.safeResourceURL;
    ck(v,5,0,currVal_2);
  });
}
function View_AudioComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-audio',([] as any[]),(null as any),(null as any),(null as any),View_AudioComponent_0,RenderType_AudioComponent)),
    import0.ɵdid(49152,(null as any),0,import6.AudioComponent,[import7.DomSanitizer],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const AudioComponentNgFactory:import0.ComponentFactory<import6.AudioComponent> = import0.ɵccf('app-audio',import6.AudioComponent,View_AudioComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9Db2xsYWIvYXVkaW8uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9Db2xsYWIvYXVkaW8uY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvam9ucm93ZS9Eb2N1bWVudHMvYW5ndWxhcjQvdmltYWxhdHYvYXNzZXRzL2FwcC9TaXRlL0NvbGxhYi9hdWRpby5jb21wb25lbnQudHMuQXVkaW9Db21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9Db2xsYWIvYXVkaW8uY29tcG9uZW50LnRzLkF1ZGlvQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgZnhGbGV4IGNsYXNzPVwiYXVkaW8tY29tcG9uZW50XCI+XG4gICAgICAgICAgICA8aWZyYW1lIHdpZHRoPVwiMTAwJVwiIGhlaWdodD1cIjE2NlwiIHNjcm9sbGluZz1cIm5vXCIgZnJhbWVib3JkZXI9XCJub1wiIFtzcmNdPVwic2FmZVJlc291cmNlVVJMXCI+PC9pZnJhbWU+XG4gICAgICAgIDwvZGl2PlxuICAgICIsIjxhcHAtYXVkaW8+PC9hcHAtYXVkaW8+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQ1E7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO2dCQUFBOzs7O01BQUE7UUFBQTs7TUFBQTs7TUFBQTtRQUFBOztNQUFBOztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtnQkFBQTs7Ozs7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFvQztJQUNoQztNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO09BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQW1HO0lBQ2pHOzs7SUFGRDtJQUFMLFNBQUssU0FBTDtJQUFZO0lBQVosU0FBWSxTQUFaOzs7SUFDc0U7SUFBbEUsU0FBa0UsU0FBbEU7Ozs7O0lDRlo7Z0JBQUE7Ozs7In0=
