/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.content-component[_ngcontent-%COMP%]{\n    height: 200px;\n    padding: 10px;\n}\n\n.top-margin[_ngcontent-%COMP%]{\n    height: 10vh;\n}\n\n.component-layout[_ngcontent-%COMP%]{\n    max-width: 960px;\n}\n\n.collab-content[_ngcontent-%COMP%]{\n    height: 100%;\n    background: url("../../../images/Vimala-Rowe-website-cover-pic-dark.jpg") no-repeat;\n    background-size: cover;\n    overflow: hidden;\n}\n\n.content-container[_ngcontent-%COMP%]{\n    overflow: auto;\n    height: calc(100vh - 96px);\n    margin: 32px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9Db2xsYWIvY29sbGFiLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvam9ucm93ZS9Eb2N1bWVudHMvYW5ndWxhcjQvdmltYWxhdHYvYXNzZXRzL2FwcC9TaXRlL0NvbGxhYi9jb2xsYWIuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
