/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './collab.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../assets/app/Site/Collab/collab.component';
import * as import3 from '@angular/router';
const styles_CollabComponent:any[] = [import0.styles];
export const RenderType_CollabComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_CollabComponent,
  data: {}
}
);
export function View_CollabComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵqud(402653184,1,{_container: 0}),
    (l()(),import1.ɵeld(0,(null as any),(null as any),8,'div',[
      [
        'class',
        'containerSite collab-content'
      ]
      ,
      [
        'fxLayout',
        'row'
      ]
      ,
      [
        'fxLayoutAlign',
        'center start'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n\n        '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),5,'div',[
      [
        'class',
        'content-container'
      ]
      ,
      [
        'fxFlex',
        '90vw'
      ]
      ,
      [
        'fxFlex.gt-sm',
        '50vw'
      ]
      ,
      [
        'fxLayout',
        'row true'
      ]
      ,
      [
        'fxLayoutAlign',
        'center start'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n            '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),0,'div',[
      [
        'class',
        'top-margin'
      ]
      ,
      [
        'fxFlex',
        '100%'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n            '])),
    (l()(),import1.ɵeld(16777216,[
      [
        1,
        3
      ]
      ,
      [
        'vc',
        1
      ]

    ]
    ,(null as any),0,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n        '])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_CollabComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'app-collab',([] as any[]),(null as any),(null as any),(null as any),View_CollabComponent_0,RenderType_CollabComponent)),
    import1.ɵdid(4440064,(null as any),0,import2.CollabComponent,[
      import1.ComponentFactoryResolver,
      import3.ActivatedRoute
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const CollabComponentNgFactory:import1.ComponentFactory<import2.CollabComponent> = import1.ɵccf('app-collab',import2.CollabComponent,View_CollabComponent_Host_0,{sub: 'collaborator'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9Db2xsYWIvY29sbGFiLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9qb25yb3dlL0RvY3VtZW50cy9hbmd1bGFyNC92aW1hbGF0di9hc3NldHMvYXBwL1NpdGUvQ29sbGFiL2NvbGxhYi5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9qb25yb3dlL0RvY3VtZW50cy9hbmd1bGFyNC92aW1hbGF0di9hc3NldHMvYXBwL1NpdGUvQ29sbGFiL2NvbGxhYi5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9Db2xsYWIvY29sbGFiLmNvbXBvbmVudC50cy5Db2xsYWJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGZ4TGF5b3V0PVwicm93XCIgZnhMYXlvdXRBbGlnbj1cImNlbnRlciBzdGFydFwiIGNsYXNzPVwiY29udGFpbmVyU2l0ZSBjb2xsYWItY29udGVudFwiPlxuXG4gICAgICAgIDxkaXYgZnhMYXlvdXQ9XCJyb3cgdHJ1ZVwiIGZ4TGF5b3V0QWxpZ249XCJjZW50ZXIgc3RhcnRcIiBmeEZsZXguZ3Qtc209XCI1MHZ3XCIgZnhGbGV4PVwiOTB2d1wiIGNsYXNzPVwiY29udGVudC1jb250YWluZXJcIj5cbiAgICAgICAgICAgIDxkaXYgZnhGbGV4PVwiMTAwJVwiIGNsYXNzPVwidG9wLW1hcmdpblwiPjwvZGl2PlxuICAgICAgICAgICAgPGRpdiAjdmM+PC9kaXY+XG4gICAgICAgIDwvZGl2PlxuPC9kaXY+IiwiPGFwcC1jb2xsYWI+PC9hcHAtY29sbGFiPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7SUFBc0Y7SUFFOUU7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO0lBQWtIO0lBQzlHO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtJQUE0QztJQUM1QztNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7SUFBZTtJQUNiOzs7Ozs7SUNMZDtnQkFBQTs7O0lBQUE7S0FBQTs7O0lBQUE7OzsifQ==
