/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/flex-layout/flexbox/api/flex';
import * as import2 from '@angular/flex-layout/media-query/media-monitor';
import * as import3 from '@angular/flex-layout/flexbox/api/layout';
import * as import4 from '@angular/flex-layout/flexbox/api/layout-wrap';
import * as import5 from '@angular/common';
import * as import6 from '../../../../../assets/app/Site/Collab/text.component';
const styles_TextComponent:any[] = ['h1[_ngcontent-%COMP%], p[_ngcontent-%COMP%] {\n                color: white;\n            }'];
export const RenderType_TextComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_TextComponent,
  data: {}
}
);
function View_TextComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    ))
  ]
  ,(null as any),(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = co.data.title;
    ck(v,1,0,currVal_0);
  });
}
export function View_TextComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n        '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),8,'div',[[
        'fxFlex',
        ''
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    import0.ɵdid(737280,(null as any),0,import1.FlexDirective,[
      import2.MediaMonitor,
      import0.ElementRef,
      import0.Renderer2,
      [
        3,
        import3.LayoutDirective
      ]
      ,
      [
        3,
        import4.LayoutWrapDirective
      ]

    ]
      ,{flex: [
        0,
        'flex'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n            '])),
    (l()(),import0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_TextComponent_1)),
    import0.ɵdid(16384,(null as any),0,import5.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n            '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵted((null as any),['\n    ']))
  ]
  ,(ck,v) => {
    var co:import6.TextComponent = v.component;
    const currVal_0:any = '';
    ck(v,2,0,currVal_0);
    const currVal_1:any = (co.data.title != (undefined as any));
    ck(v,5,0,currVal_1);
  },(ck,v) => {
    var co:import6.TextComponent = v.component;
    const currVal_2:any = co.data.content;
    ck(v,8,0,currVal_2);
  });
}
function View_TextComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-text',([] as any[]),(null as any),(null as any),(null as any),View_TextComponent_0,RenderType_TextComponent)),
    import0.ɵdid(49152,(null as any),0,import6.TextComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const TextComponentNgFactory:import0.ComponentFactory<import6.TextComponent> = import0.ɵccf('app-text',import6.TextComponent,View_TextComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9Db2xsYWIvdGV4dC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvam9ucm93ZS9Eb2N1bWVudHMvYW5ndWxhcjQvdmltYWxhdHYvYXNzZXRzL2FwcC9TaXRlL0NvbGxhYi90ZXh0LmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9Db2xsYWIvdGV4dC5jb21wb25lbnQudHMuVGV4dENvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvam9ucm93ZS9Eb2N1bWVudHMvYW5ndWxhcjQvdmltYWxhdHYvYXNzZXRzL2FwcC9TaXRlL0NvbGxhYi90ZXh0LmNvbXBvbmVudC50cy5UZXh0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgZnhGbGV4PlxuICAgICAgICAgICAgPGgxICpuZ0lmPVwiZGF0YS50aXRsZSAhPSB1bmRlZmluZWRcIj57e2RhdGEudGl0bGV9fTwvaDE+XG4gICAgICAgICAgICA8cD57e2RhdGEuY29udGVudH19PC9wPlxuICAgICAgICA8L2Rpdj5cbiAgICAiLCI8YXBwLXRleHQ+PC9hcHAtdGV4dD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNFWTtJQUFvQztNQUFBO01BQUE7SUFBQTtJQUFBOzs7O0lBQUE7SUFBQTs7Ozs7SUFGaEQ7TUFDUTtRQUFBO1FBQUE7TUFBQTtJQUFBO2dCQUFBOzs7O01BQUE7UUFBQTs7TUFBQTs7TUFBQTtRQUFBOztNQUFBOztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFZO0lBQ1I7Z0JBQUE7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF1RDtJQUN2RDtJQUFHO01BQUE7TUFBQTtJQUFBO0lBQUE7SUFBb0I7SUFDckI7Ozs7SUFIRDtJQUFMLFNBQUssU0FBTDtJQUNRO0lBQUosU0FBSSxTQUFKOzs7SUFDRztJQUFBOzs7OztJQ0hmO2dCQUFBOzs7OyJ9
