/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './contact.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../assets/app/Site/Contact/contact.component';
const styles_ContactComponent:any[] = [import0.styles];
export const RenderType_ContactComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_ContactComponent,
  data: {}
}
);
export function View_ContactComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[(l()(),import1.ɵted((null as any),['Contact']))],(null as any),(null as any));
}
function View_ContactComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'app-contact',([] as any[]),(null as any),(null as any),(null as any),View_ContactComponent_0,RenderType_ContactComponent)),
    import1.ɵdid(49152,(null as any),0,import2.ContactComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const ContactComponentNgFactory:import1.ComponentFactory<import2.ContactComponent> = import1.ɵccf('app-contact',import2.ContactComponent,View_ContactComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9Db250YWN0L2NvbnRhY3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9Db250YWN0L2NvbnRhY3QuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvam9ucm93ZS9Eb2N1bWVudHMvYW5ndWxhcjQvdmltYWxhdHYvYXNzZXRzL2FwcC9TaXRlL0NvbnRhY3QvY29udGFjdC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9Db250YWN0L2NvbnRhY3QuY29tcG9uZW50LnRzLkNvbnRhY3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJDb250YWN0IiwiPGFwcC1jb250YWN0PjwvYXBwLWNvbnRhY3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5QkNBQTs7OztJQ0FBO2dCQUFBOzs7OyJ9
