/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './home.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '@angular/flex-layout/flexbox/api/layout-align';
import * as import3 from '@angular/flex-layout/media-query/media-monitor';
import * as import4 from '@angular/flex-layout/flexbox/api/flex';
import * as import5 from '@angular/flex-layout/flexbox/api/layout';
import * as import6 from '@angular/flex-layout/flexbox/api/layout-wrap';
import * as import7 from '@angular/flex-layout/flexbox/api/class';
import * as import8 from '@angular/flex-layout/flexbox/api/flex-align';
import * as import9 from '../../../../../assets/app/CMS/home/home.component';
const styles_HomeComponent:any[] = [import0.styles];
export const RenderType_HomeComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_HomeComponent,
  data: {}
}
);
export function View_HomeComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),12,'div',[
      [
        'class',
        'containerCMS'
      ]
      ,
      [
        'fxFlex',
        '1 1 auto'
      ]
      ,
      [
        'fxLayoutAlign',
        'column'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    import1.ɵdid(737280,(null as any),0,import2.LayoutAlignDirective,[
      import3.MediaMonitor,
      import1.ElementRef,
      import1.Renderer2,
      [
        8,
        (null as any)
      ]

    ]
      ,{align: [
        0,
        'align'
      ]
    },(null as any)),
    import1.ɵdid(737280,(null as any),0,import4.FlexDirective,[
      import3.MediaMonitor,
      import1.ElementRef,
      import1.Renderer2,
      [
        3,
        import5.LayoutDirective
      ]
      ,
      [
        3,
        import6.LayoutWrapDirective
      ]

    ]
      ,{flex: [
        0,
        'flex'
      ]
    },(null as any)),
    import1.ɵdid(933888,(null as any),0,import7.ClassDirective,[
      import3.MediaMonitor,
      import1.IterableDiffers,
      import1.KeyValueDiffers,
      import1.ElementRef,
      import1.Renderer,
      import1.Renderer2
    ]
      ,{classBase: [
        0,
        'classBase'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),6,'div',[
      [
        'fxFlex',
        '1 1 auto'
      ]
      ,
      [
        'fxFlexAlign',
        'center'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    import1.ɵdid(737280,(null as any),0,import4.FlexDirective,[
      import3.MediaMonitor,
      import1.ElementRef,
      import1.Renderer2,
      [
        3,
        import5.LayoutDirective
      ]
      ,
      [
        3,
        import6.LayoutWrapDirective
      ]

    ]
      ,{flex: [
        0,
        'flex'
      ]
    },(null as any)),
    import1.ɵdid(737280,(null as any),0,import8.FlexAlignDirective,[
      import3.MediaMonitor,
      import1.ElementRef,
      import1.Renderer2
    ]
      ,{align: [
        0,
        'align'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),['\n        '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['No user configurable items for this page'])),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    const currVal_0:any = 'column';
    ck(v,1,0,currVal_0);
    const currVal_1:any = '1 1 auto';
    ck(v,2,0,currVal_1);
    const currVal_2:any = 'containerCMS';
    ck(v,3,0,currVal_2);
    const currVal_3:any = '1 1 auto';
    ck(v,6,0,currVal_3);
    const currVal_4:any = 'center';
    ck(v,7,0,currVal_4);
  },(null as any));
}
function View_HomeComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'cms-home',([] as any[]),(null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent)),
    import1.ɵdid(49152,(null as any),0,import9.HomeComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HomeComponentNgFactory:import1.ComponentFactory<import9.HomeComponent> = import1.ɵccf('cms-home',import9.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvQ01TL2hvbWUvaG9tZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvam9ucm93ZS9Eb2N1bWVudHMvYW5ndWxhcjQvdmltYWxhdHYvYXNzZXRzL2FwcC9DTVMvaG9tZS9ob21lLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvQ01TL2hvbWUvaG9tZS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvQ01TL2hvbWUvaG9tZS5jb21wb25lbnQudHMuSG9tZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJjb250YWluZXJDTVNcIiBmeExheW91dEFsaWduPVwiY29sdW1uXCIgZnhGbGV4PVwiMSAxIGF1dG9cIj5cbiAgICA8ZGl2IGZ4RmxleD1cIjEgMSBhdXRvXCIgZnhGbGV4QWxpZ249XCJjZW50ZXJcIj5cbiAgICAgICAgPHA+Tm8gdXNlciBjb25maWd1cmFibGUgaXRlbXMgZm9yIHRoaXMgcGFnZTwvcD5cbiAgICA8L2Rpdj5cbjwvZGl2PiIsIjxjbXMtaG9tZT48L2Ntcy1ob21lPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtnQkFBQTs7OztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtnQkFBQTs7OztNQUFBO1FBQUE7O01BQUE7O01BQUE7UUFBQTs7TUFBQTs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7Z0JBQUE7Ozs7Ozs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBbUU7SUFDL0Q7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO2dCQUFBOzs7O01BQUE7UUFBQTs7TUFBQTs7TUFBQTtRQUFBOztNQUFBOztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtnQkFBQTs7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUE0QztJQUN4QztJQUFHO0lBQTRDO0lBQzdDOzs7SUFIZ0I7SUFBMUIsU0FBMEIsU0FBMUI7SUFBaUQ7SUFBakQsU0FBaUQsU0FBakQ7SUFBSztJQUFMLFNBQUssU0FBTDtJQUNTO0lBQUwsU0FBSyxTQUFMO0lBQXVCO0lBQXZCLFNBQXVCLFNBQXZCOzs7OztJQ0RKO2dCQUFBOzs7OyJ9
