/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './media.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../assets/app/Site/Media/media.component';
const styles_MediaComponent:any[] = [import0.styles];
export const RenderType_MediaComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_MediaComponent,
  data: {}
}
);
export function View_MediaComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[(l()(),import1.ɵted((null as any),['Media']))],(null as any),(null as any));
}
function View_MediaComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'app-media',([] as any[]),(null as any),(null as any),(null as any),View_MediaComponent_0,RenderType_MediaComponent)),
    import1.ɵdid(49152,(null as any),0,import2.MediaComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const MediaComponentNgFactory:import1.ComponentFactory<import2.MediaComponent> = import1.ɵccf('app-media',import2.MediaComponent,View_MediaComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9NZWRpYS9tZWRpYS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvam9ucm93ZS9Eb2N1bWVudHMvYW5ndWxhcjQvdmltYWxhdHYvYXNzZXRzL2FwcC9TaXRlL01lZGlhL21lZGlhLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9NZWRpYS9tZWRpYS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9NZWRpYS9tZWRpYS5jb21wb25lbnQudHMuTWVkaWFDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJNZWRpYSIsIjxhcHAtbWVkaWE+PC9hcHAtbWVkaWE+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5QkNBQTs7OztJQ0FBO2dCQUFBOzs7OyJ9
