/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './reviews.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../assets/app/Site/Reviews/reviews.component';
const styles_ReviewsComponent:any[] = [import0.styles];
export const RenderType_ReviewsComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_ReviewsComponent,
  data: {}
}
);
export function View_ReviewsComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[(l()(),import1.ɵted((null as any),['Reviews']))],(null as any),(null as any));
}
function View_ReviewsComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'app-reviews',([] as any[]),(null as any),(null as any),(null as any),View_ReviewsComponent_0,RenderType_ReviewsComponent)),
    import1.ɵdid(49152,(null as any),0,import2.ReviewsComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const ReviewsComponentNgFactory:import1.ComponentFactory<import2.ReviewsComponent> = import1.ɵccf('app-reviews',import2.ReviewsComponent,View_ReviewsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9SZXZpZXdzL3Jldmlld3MuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9SZXZpZXdzL3Jldmlld3MuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvam9ucm93ZS9Eb2N1bWVudHMvYW5ndWxhcjQvdmltYWxhdHYvYXNzZXRzL2FwcC9TaXRlL1Jldmlld3MvcmV2aWV3cy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9SZXZpZXdzL3Jldmlld3MuY29tcG9uZW50LnRzLlJldmlld3NDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJSZXZpZXdzIiwiPGFwcC1yZXZpZXdzPjwvYXBwLXJldmlld3M+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5QkNBQTs7OztJQ0FBO2dCQUFBOzs7OyJ9
