/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../assets/app/common.module';
class CommonModuleInjector extends import0.ɵNgModuleInjector<import1.CommonModule> {
  _CommonModule_0:import1.CommonModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.CommonModule {
    this._CommonModule_0 = new import1.CommonModule();
    return this._CommonModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.CommonModule)) { return this._CommonModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const CommonModuleNgFactory:import0.NgModuleFactory<import1.CommonModule> = new import0.NgModuleFactory<any>(CommonModuleInjector,import1.CommonModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvY29tbW9uLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9qb25yb3dlL0RvY3VtZW50cy9hbmd1bGFyNC92aW1hbGF0di9hc3NldHMvYXBwL2NvbW1vbi5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
