/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './bio.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../assets/app/Site/Bio/bio.component';
const styles_BioComponent:any[] = [import0.styles];
export const RenderType_BioComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_BioComponent,
  data: {}
}
);
export function View_BioComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[(l()(),import1.ɵted((null as any),['Bio']))],(null as any),(null as any));
}
function View_BioComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'app-bio',([] as any[]),(null as any),(null as any),(null as any),View_BioComponent_0,RenderType_BioComponent)),
    import1.ɵdid(49152,(null as any),0,import2.BioComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const BioComponentNgFactory:import1.ComponentFactory<import2.BioComponent> = import1.ɵccf('app-bio',import2.BioComponent,View_BioComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9CaW8vYmlvLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9qb25yb3dlL0RvY3VtZW50cy9hbmd1bGFyNC92aW1hbGF0di9hc3NldHMvYXBwL1NpdGUvQmlvL2Jpby5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9qb25yb3dlL0RvY3VtZW50cy9hbmd1bGFyNC92aW1hbGF0di9hc3NldHMvYXBwL1NpdGUvQmlvL2Jpby5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvU2l0ZS9CaW8vYmlvLmNvbXBvbmVudC50cy5CaW9Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJCaW8iLCI8YXBwLWJpbz48L2FwcC1iaW8+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5QkNBQTs7OztJQ0FBO2dCQUFBOzs7OyJ9
