/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './media.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../assets/app/CMS/media/media.component';
const styles_MediaComponent:any[] = [import0.styles];
export const RenderType_MediaComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_MediaComponent,
  data: {}
}
);
export function View_MediaComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    MEDIA\n']))
  ]
  ,(null as any),(null as any));
}
function View_MediaComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'cms-media',([] as any[]),(null as any),(null as any),(null as any),View_MediaComponent_0,RenderType_MediaComponent)),
    import1.ɵdid(49152,(null as any),0,import2.MediaComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const MediaComponentNgFactory:import1.ComponentFactory<import2.MediaComponent> = import1.ɵccf('cms-media',import2.MediaComponent,View_MediaComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvQ01TL21lZGlhL21lZGlhLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9qb25yb3dlL0RvY3VtZW50cy9hbmd1bGFyNC92aW1hbGF0di9hc3NldHMvYXBwL0NNUy9tZWRpYS9tZWRpYS5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9qb25yb3dlL0RvY3VtZW50cy9hbmd1bGFyNC92aW1hbGF0di9hc3NldHMvYXBwL0NNUy9tZWRpYS9tZWRpYS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2pvbnJvd2UvRG9jdW1lbnRzL2FuZ3VsYXI0L3ZpbWFsYXR2L2Fzc2V0cy9hcHAvQ01TL21lZGlhL21lZGlhLmNvbXBvbmVudC50cy5NZWRpYUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXY+XG4gICAgTUVESUFcbjwvZGl2PiIsIjxjbXMtbWVkaWE+PC9jbXMtbWVkaWE+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFLOzs7Ozs7SUNBTDtnQkFBQTs7OzsifQ==
